// <auto-generated />
using System;
using CEProjectServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CEProjectServer.Migrations
{
    [DbContext(typeof(CEContext))]
    [Migration("20230607111136_init!")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CEProjectServer.AnalyticModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreationCount")
                        .HasColumnType("int");

                    b.Property<string>("DownloadURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Downloads")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LatestDownload")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganisationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Analytics");
                });

            modelBuilder.Entity("CEProjectServer.EconomicFactorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Factor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FactorValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("EconomicFactors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Factor = "Deadweight Factor",
                            FactorValue = 19.0
                        },
                        new
                        {
                            Id = 2,
                            Factor = "Conversion Factor",
                            FactorValue = 10.0
                        });
                });

            modelBuilder.Entity("CEProjectServer.InterventionEffectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EffectValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("InterventionEffects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EffectType = "Social network",
                            EffectValue = 2.6600000000000001
                        },
                        new
                        {
                            Id = 2,
                            EffectType = "Social support",
                            EffectValue = 3.46
                        },
                        new
                        {
                            Id = 3,
                            EffectType = "Social and emotional skills training",
                            EffectValue = 3.3700000000000001
                        },
                        new
                        {
                            Id = 4,
                            EffectType = "Psychological treatment",
                            EffectValue = 4.4299999999999997
                        },
                        new
                        {
                            Id = 5,
                            EffectType = "Unspecified",
                            EffectValue = 3.48
                        },
                        new
                        {
                            Id = 6,
                            EffectType = "Own specification",
                            EffectValue = 0.0
                        });
                });

            modelBuilder.Entity("CEProjectServer.MeasurementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MeasurementModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MeasurementType = "N scale"
                        },
                        new
                        {
                            Id = 2,
                            MeasurementType = "UCLA Loneliness Scale"
                        });
                });

            modelBuilder.Entity("CEProjectServer.PopulationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PopulationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Populations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PopulationType = "General Population"
                        },
                        new
                        {
                            Id = 2,
                            PopulationType = "Youth 0-15"
                        },
                        new
                        {
                            Id = 3,
                            PopulationType = "Working age16-64"
                        },
                        new
                        {
                            Id = 4,
                            PopulationType = "Population 65+"
                        });
                });

            modelBuilder.Entity("CEProjectServer.SectorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SectorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sectors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SectorType = "Healthcare"
                        },
                        new
                        {
                            Id = 2,
                            SectorType = "Sick days"
                        },
                        new
                        {
                            Id = 3,
                            SectorType = "Unemployment"
                        },
                        new
                        {
                            Id = 4,
                            SectorType = "Wellbeing"
                        });
                });

            modelBuilder.Entity("CEProjectServer.StakeholderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StakeholderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stakeholders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StakeholderType = "Municipality"
                        },
                        new
                        {
                            Id = 2,
                            StakeholderType = "Region"
                        },
                        new
                        {
                            Id = 3,
                            StakeholderType = "Other state"
                        },
                        new
                        {
                            Id = 4,
                            StakeholderType = "Other economic"
                        },
                        new
                        {
                            Id = 5,
                            StakeholderType = "Monetary quality of life"
                        },
                        new
                        {
                            Id = 6,
                            StakeholderType = "Production"
                        });
                });

            modelBuilder.Entity("CEProjectServer.TotalSectorCostModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeasurementModelId")
                        .HasColumnType("int");

                    b.Property<int>("PopulationModelId")
                        .HasColumnType("int");

                    b.Property<int>("SectorModelId")
                        .HasColumnType("int");

                    b.Property<int>("StakeholderModelId")
                        .HasColumnType("int");

                    b.Property<double>("TotalSectorCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementModelId");

                    b.HasIndex("PopulationModelId");

                    b.HasIndex("SectorModelId");

                    b.HasIndex("StakeholderModelId");

                    b.ToTable("TotalSectorCosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 1.385
                        },
                        new
                        {
                            Id = 2,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 3,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 185.0
                        },
                        new
                        {
                            Id = 4,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 6.2469999999999999
                        },
                        new
                        {
                            Id = 5,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 8.0559999999999992
                        },
                        new
                        {
                            Id = 6,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 7.6420000000000003
                        },
                        new
                        {
                            Id = 7,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 7.7750000000000004
                        },
                        new
                        {
                            Id = 8,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 9.2680000000000007
                        },
                        new
                        {
                            Id = 9,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 10,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 11,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 12,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 13,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 14,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 15,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 16,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 17,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 979.0
                        },
                        new
                        {
                            Id = 18,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 19,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 1.5700000000000001
                        },
                        new
                        {
                            Id = 20,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 21,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 22,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 23,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 24,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 25,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 26,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 27,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 28,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 29,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 4.5220000000000002
                        },
                        new
                        {
                            Id = 30,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 31,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 7.2489999999999997
                        },
                        new
                        {
                            Id = 32,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 33,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 306.0
                        },
                        new
                        {
                            Id = 34,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 35,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 491.0
                        },
                        new
                        {
                            Id = 36,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 37,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 38,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 39,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 40,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 41,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 2.2210000000000001
                        },
                        new
                        {
                            Id = 42,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 43,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 3.5609999999999999
                        },
                        new
                        {
                            Id = 44,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 45,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 7.9729999999999999
                        },
                        new
                        {
                            Id = 46,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 47,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 12.782999999999999
                        },
                        new
                        {
                            Id = 48,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 49,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 50,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 51,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 52,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 53,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 54,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 55,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 56,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 57,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 58,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 59,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 60,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 61,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 195.63399999999999
                        },
                        new
                        {
                            Id = 62,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 195.63399999999999
                        },
                        new
                        {
                            Id = 63,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 195.63399999999999
                        },
                        new
                        {
                            Id = 64,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 195.63399999999999
                        },
                        new
                        {
                            Id = 65,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 46.0
                        },
                        new
                        {
                            Id = 66,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 67,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 6.0
                        },
                        new
                        {
                            Id = 68,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 208.0
                        },
                        new
                        {
                            Id = 69,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 269.0
                        },
                        new
                        {
                            Id = 70,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 255.0
                        },
                        new
                        {
                            Id = 71,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 259.0
                        },
                        new
                        {
                            Id = 72,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 309.0
                        },
                        new
                        {
                            Id = 73,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 74,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 75,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 76,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 77,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 78,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 79,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 80,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 81,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 33.0
                        },
                        new
                        {
                            Id = 82,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 83,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 52.0
                        },
                        new
                        {
                            Id = 84,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 85,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 86,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 87,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 88,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 89,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 90,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 91,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 92,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 93,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 151.0
                        },
                        new
                        {
                            Id = 94,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 95,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 242.0
                        },
                        new
                        {
                            Id = 96,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 97,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 10.0
                        },
                        new
                        {
                            Id = 98,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 99,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 16.0
                        },
                        new
                        {
                            Id = 100,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 101,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 102,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 103,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 104,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 105,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 74.0
                        },
                        new
                        {
                            Id = 106,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 107,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 119.0
                        },
                        new
                        {
                            Id = 108,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 109,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 266.0
                        },
                        new
                        {
                            Id = 110,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 111,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 426.0
                        },
                        new
                        {
                            Id = 112,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 113,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 114,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 115,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 116,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 117,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 118,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 119,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 120,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 121,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 122,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 123,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 124,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0.0
                        },
                        new
                        {
                            Id = 125,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 6.5209999999999999
                        },
                        new
                        {
                            Id = 126,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 6.5209999999999999
                        },
                        new
                        {
                            Id = 127,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 6.5209999999999999
                        },
                        new
                        {
                            Id = 128,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 6.5209999999999999
                        });
                });

            modelBuilder.Entity("CEProjectServer.TotalSectorCostModel", b =>
                {
                    b.HasOne("CEProjectServer.MeasurementModel", "MeasurementModel")
                        .WithMany("TotalSectorCostModel")
                        .HasForeignKey("MeasurementModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CEProjectServer.PopulationModel", "PopulationModel")
                        .WithMany("TotalSectorCostModel")
                        .HasForeignKey("PopulationModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CEProjectServer.SectorModel", "SectorModel")
                        .WithMany("TotalSectorCostModel")
                        .HasForeignKey("SectorModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CEProjectServer.StakeholderModel", "StakeholderModel")
                        .WithMany("TotalSectorCostModel")
                        .HasForeignKey("StakeholderModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MeasurementModel");

                    b.Navigation("PopulationModel");

                    b.Navigation("SectorModel");

                    b.Navigation("StakeholderModel");
                });

            modelBuilder.Entity("CEProjectServer.MeasurementModel", b =>
                {
                    b.Navigation("TotalSectorCostModel");
                });

            modelBuilder.Entity("CEProjectServer.PopulationModel", b =>
                {
                    b.Navigation("TotalSectorCostModel");
                });

            modelBuilder.Entity("CEProjectServer.SectorModel", b =>
                {
                    b.Navigation("TotalSectorCostModel");
                });

            modelBuilder.Entity("CEProjectServer.StakeholderModel", b =>
                {
                    b.Navigation("TotalSectorCostModel");
                });
#pragma warning restore 612, 618
        }
    }
}
