// <auto-generated />
using System;
using CEProjectServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CEProjectServer.Migrations
{
    [DbContext(typeof(CEContext))]
    [Migration("20230626135936_upseedforInterventionType")]
    partial class upseedforInterventionType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CEProjectServer.AnalyticModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreationCount")
                        .HasColumnType("int");

                    b.Property<string>("DownloadURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Downloads")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LatestDownload")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrganisationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganisationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Analytics");
                });

            modelBuilder.Entity("CEProjectServer.EconomicFactorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Factor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FactorValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EconomicFactors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Factor = "Deadweight Factor",
                            FactorValue = 19m
                        },
                        new
                        {
                            Id = 2,
                            Factor = "Deadweight Factor",
                            FactorValue = 1m
                        });
                });

            modelBuilder.Entity("CEProjectServer.InterventionEffectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EffectValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("InterventionEffects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EffectType = "Social network",
                            EffectValue = 2.65923970302888m
                        },
                        new
                        {
                            Id = 2,
                            EffectType = "Social support",
                            EffectValue = 3.45701161393755m
                        },
                        new
                        {
                            Id = 3,
                            EffectType = "Social and emotional skills training",
                            EffectValue = 3.36837029050325m
                        },
                        new
                        {
                            Id = 4,
                            EffectType = "Psychological treatment",
                            EffectValue = 4.4320661717148m
                        },
                        new
                        {
                            Id = 5,
                            EffectType = "Unspecified",
                            EffectValue = 3.47917194479612m
                        },
                        new
                        {
                            Id = 6,
                            EffectType = "Own specification",
                            EffectValue = 0m
                        });
                });

            modelBuilder.Entity("CEProjectServer.MeasurementModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MeasurementModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MeasurementType = "N scale"
                        },
                        new
                        {
                            Id = 2,
                            MeasurementType = "UCLA Loneliness Scale"
                        });
                });

            modelBuilder.Entity("CEProjectServer.PopulationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PopulationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Populations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PopulationType = "General Population"
                        },
                        new
                        {
                            Id = 2,
                            PopulationType = "Youth 0-15"
                        },
                        new
                        {
                            Id = 3,
                            PopulationType = "Working age16-64"
                        },
                        new
                        {
                            Id = 4,
                            PopulationType = "Population 65+"
                        });
                });

            modelBuilder.Entity("CEProjectServer.SectorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SectorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sectors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SectorType = "Healthcare"
                        },
                        new
                        {
                            Id = 2,
                            SectorType = "Sick days"
                        },
                        new
                        {
                            Id = 3,
                            SectorType = "Unemployment"
                        },
                        new
                        {
                            Id = 4,
                            SectorType = "Wellbeing"
                        });
                });

            modelBuilder.Entity("CEProjectServer.StakeholderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StakeholderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stakeholders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StakeholderType = "Municipality"
                        },
                        new
                        {
                            Id = 2,
                            StakeholderType = "Region"
                        },
                        new
                        {
                            Id = 3,
                            StakeholderType = "Other state"
                        },
                        new
                        {
                            Id = 4,
                            StakeholderType = "Other economic"
                        },
                        new
                        {
                            Id = 5,
                            StakeholderType = "Monetary quality of life"
                        },
                        new
                        {
                            Id = 6,
                            StakeholderType = "Production"
                        });
                });

            modelBuilder.Entity("CEProjectServer.TotalSectorCostModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MeasurementModelId")
                        .HasColumnType("int");

                    b.Property<int>("PopulationModelId")
                        .HasColumnType("int");

                    b.Property<int>("SectorModelId")
                        .HasColumnType("int");

                    b.Property<int>("StakeholderModelId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSectorCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementModelId");

                    b.HasIndex("PopulationModelId");

                    b.HasIndex("SectorModelId");

                    b.HasIndex("StakeholderModelId");

                    b.ToTable("TotalSectorCosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 1385m
                        },
                        new
                        {
                            Id = 2,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 3,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 185m
                        },
                        new
                        {
                            Id = 4,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 6247m
                        },
                        new
                        {
                            Id = 5,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 8056m
                        },
                        new
                        {
                            Id = 6,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 7642m
                        },
                        new
                        {
                            Id = 7,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 7775m
                        },
                        new
                        {
                            Id = 8,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 9268m
                        },
                        new
                        {
                            Id = 9,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 10,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 11,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 12,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 13,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 14,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 15,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 16,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 17,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 979m
                        },
                        new
                        {
                            Id = 18,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 19,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 1570m
                        },
                        new
                        {
                            Id = 20,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 21,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 22,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 23,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 24,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 25,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 26,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 27,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 28,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 29,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 4522m
                        },
                        new
                        {
                            Id = 30,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 31,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 7249m
                        },
                        new
                        {
                            Id = 32,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 33,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 306m
                        },
                        new
                        {
                            Id = 34,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 35,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 491m
                        },
                        new
                        {
                            Id = 36,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 37,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 38,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 39,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 40,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 41,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 2221m
                        },
                        new
                        {
                            Id = 42,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 43,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 3561m
                        },
                        new
                        {
                            Id = 44,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 45,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 7973m
                        },
                        new
                        {
                            Id = 46,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 47,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 12783m
                        },
                        new
                        {
                            Id = 48,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 49,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 50,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 51,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 52,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 53,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 54,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 55,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 56,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 57,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 58,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 59,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 60,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 61,
                            MeasurementModelId = 1,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 286000m
                        },
                        new
                        {
                            Id = 62,
                            MeasurementModelId = 1,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 286000m
                        },
                        new
                        {
                            Id = 63,
                            MeasurementModelId = 1,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 286000m
                        },
                        new
                        {
                            Id = 64,
                            MeasurementModelId = 1,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 286000m
                        },
                        new
                        {
                            Id = 65,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 46m
                        },
                        new
                        {
                            Id = 66,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 67,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 6m
                        },
                        new
                        {
                            Id = 68,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 1,
                            TotalSectorCost = 208m
                        },
                        new
                        {
                            Id = 69,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 269m
                        },
                        new
                        {
                            Id = 70,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 255m
                        },
                        new
                        {
                            Id = 71,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 259m
                        },
                        new
                        {
                            Id = 72,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 2,
                            TotalSectorCost = 309m
                        },
                        new
                        {
                            Id = 73,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 74,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 75,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 76,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 77,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 78,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 79,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 80,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 1,
                            StakeholderModelId = 4,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 81,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 33m
                        },
                        new
                        {
                            Id = 82,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 83,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 52m
                        },
                        new
                        {
                            Id = 84,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 85,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 86,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 87,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 88,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 89,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 90,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 91,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 92,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 93,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 151m
                        },
                        new
                        {
                            Id = 94,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 95,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 242m
                        },
                        new
                        {
                            Id = 96,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 2,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 97,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 10m
                        },
                        new
                        {
                            Id = 98,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 99,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 16m
                        },
                        new
                        {
                            Id = 100,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 101,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 102,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 103,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 104,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 105,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 74m
                        },
                        new
                        {
                            Id = 106,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 107,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 119m
                        },
                        new
                        {
                            Id = 108,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 109,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 266m
                        },
                        new
                        {
                            Id = 110,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 111,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 426m
                        },
                        new
                        {
                            Id = 112,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 3,
                            StakeholderModelId = 6,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 113,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 114,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 115,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 116,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 1,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 117,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 118,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 119,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 120,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 2,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 121,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 122,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 123,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 124,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 3,
                            TotalSectorCost = 0m
                        },
                        new
                        {
                            Id = 125,
                            MeasurementModelId = 2,
                            PopulationModelId = 1,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 9533m
                        },
                        new
                        {
                            Id = 126,
                            MeasurementModelId = 2,
                            PopulationModelId = 2,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 9533m
                        },
                        new
                        {
                            Id = 127,
                            MeasurementModelId = 2,
                            PopulationModelId = 3,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 9533m
                        },
                        new
                        {
                            Id = 128,
                            MeasurementModelId = 2,
                            PopulationModelId = 4,
                            SectorModelId = 4,
                            StakeholderModelId = 5,
                            TotalSectorCost = 9533m
                        });
                });

            modelBuilder.Entity("CEProjectServer.TotalSectorCostModel", b =>
                {
                    b.HasOne("CEProjectServer.MeasurementModel", "MeasurementModel")
                        .WithMany("TotalSectorCostModel")
                        .HasForeignKey("MeasurementModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CEProjectServer.PopulationModel", "PopulationModel")
                        .WithMany("TotalSectorCostModel")
                        .HasForeignKey("PopulationModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CEProjectServer.SectorModel", "SectorModel")
                        .WithMany("TotalSectorCostModel")
                        .HasForeignKey("SectorModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CEProjectServer.StakeholderModel", "StakeholderModel")
                        .WithMany("TotalSectorCostModel")
                        .HasForeignKey("StakeholderModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MeasurementModel");

                    b.Navigation("PopulationModel");

                    b.Navigation("SectorModel");

                    b.Navigation("StakeholderModel");
                });

            modelBuilder.Entity("CEProjectServer.MeasurementModel", b =>
                {
                    b.Navigation("TotalSectorCostModel");
                });

            modelBuilder.Entity("CEProjectServer.PopulationModel", b =>
                {
                    b.Navigation("TotalSectorCostModel");
                });

            modelBuilder.Entity("CEProjectServer.SectorModel", b =>
                {
                    b.Navigation("TotalSectorCostModel");
                });

            modelBuilder.Entity("CEProjectServer.StakeholderModel", b =>
                {
                    b.Navigation("TotalSectorCostModel");
                });
#pragma warning restore 612, 618
        }
    }
}
